version: '3.4'

services:
  wordpress:
    build: .
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: ./docker_vhosts/
        target: /etc/apache2/sites-available/
    depends_on:
      - db
      - phpmyadmin
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
volumes:
  wordpress:
  db:
  phpmyadmin: